[package]
name = "d"
version = "0.1.0"
authors = ["max"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    postgres = { git = "https://github.com/sfackler/rust-postgres.git" }