mysql:
  host: 'localhost'
  ip: '127.0.0.1'
  port: 3306
  db: 'db'
  user: 'root'
  passwd: 'mypasswd'

postgres:
  host: 'localhost'
  ip: '127.0.0.1'
  port: 5432
  db: 'db'
  user: 'root'
  passwd: 'mypasswd'

